### ISSUE TITLE
EPIC Library authentication fails - using EPIC log in (can't import games).

### ISSUE THREAD

**Issue by FenDIY** [JosefNemec/PlayniteExtensions#54]
The issue happens sometimes (not 100% of the time).
When importing games for the EPIC Library, the authentication fails (the bell shows the number 1).
   

1. When clicking the bell it reads "... EPIC... An error occurred while sending the request".
2. When clicking on the "EPIC..."message, I can see a pop-up dialog with a button that says [Authenticate] and a message to its right reading "Checking Authentication Status...". 
2a. Most of the times it resolves to "Authenticated".
2b. Sometimes it resolves to "Requires authentication". Then I click the button, fill in all the details and it resolves to "Authenticated".
3. Still, after being Authenticated, trying again to import from library fails, and I need to start all over again. 

Things I've tried:
 - Disabling the plugin (EPIC).
 - Playnite safe mode (as requested).
 - restarting the app a few times.
 - log in to EPIC with the EPIC login (not the google one, or any other). **It fails!**.
 - log in to EPIC through the Web browser and the app (**successfully** in all those cases).
 - Updating the app (both. EPIC launcher, and playnite).
 - Everything has been restarted 2 or 3 times at least (browser, app, playnite)
 - Most other libraries work fine without issue. But sometimes might have the log in issue as well, from time to time. But all the log in issues of the other libraries (not counting EPIC) together  are 1/3-1/2 the issues with EPIC (maybe it's EPIC's site, maybe the integration).
 - Tried several times to import. Sometimes it works on the 4th/5th try, sometimes on the 2nd, sometimes ... on the 20th.

Please note, that I have a very restrictive firewall in place. 
Playnite is running as a browser (So ports: 80, 443, 53, 21, and some other. That should suffice), but I had it running as a full outbound/inbound app as well (just for testing). The issues were the same.
But I have also blocked (for years now, and different systems and windows versions) "system" (whatever that means on the firewall) and svchost.exe (only the DNS port and some basic ports are allowed) NEVER AN ISSUE (for windows update, I do allow some IPs when needed).
If it were a firewall problem, please let us know what processes and ports are needed through, so we can act accordingly. Thanks.

EPIC used to log in using some windows processes (maybe svchost, maybe windows update processes). I did contact them about that, and they told me so, and that they were working on an alternative (which is the way it's working now). So no issue there either.

- [x] **Check for an existing issue**
- [x] **Describe the bug**
- [x] **To Reproduce**
- [ ] **Screenshots**
- [x] **Diagnostics ID:** 87c0277e-de3a-46cf-a392-b888c83bb7b2

PS: Just mentioning that as of now it's working (I don't know for how long). And no wifi is used. Cat-6 cable.

**Comment by JosefNemec** [comment]
This is network issue according to logs, nothing I can fix. It's either an issue on Epic's side or in your environment.
```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 3.223.58.23:443
```

**Comment by FenDIY** [comment]
Ok, thanks. Then sorry about that. I'll check the network for issues.
Is there a way for me to be able to see the logs?

**Comment by FenDIY** [comment]
Nevermind, I'll try to find it!
Thanks.

PS:I'll keep the issue open until I do some tests and see the results on the logs to make sure of it. ^_^

**Comment by JosefNemec** [comment]
Logs are in `%appdata%\playnite\playnite.log` if you are using installed version.

**Comment by joyrider3774** [comment]
just tested on p9 beta and p8 both exhibit the same problem with me as well displaying authentication failed so it's not related to the beta, could be an issue with epic or they have changed something

**Comment by SilverRoll** [comment]
joyrider3774 on discord says this is also broken on P8. I'd close this, but it's up to you

**Comment by JosefNemec** [comment]
The issue that started happening today is not the same as original issue reported here, which is clearly caused by network error.

**Comment by joyrider3774** [comment]
> The issue that started happening today is not the same as original issue reported here, which is clearly caused by network error.

someone gave me wrong link to issue then on discord, i asked if it was reported

**Comment by JosefNemec** [comment]
Closing, authentication right now works properly. The original issue is caused by a network issue, which is something we can't do anything about.
